---
title: "Reproducibility check"
author: "NEST CoreDev"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reproducibility check}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Reproducibility check

## Mechanism

`teal_data` objects instantiated with data and code run the risk of the code not being reproducible.
Such objects will be created in an _unverified_ state. 
To confirm that the code exactly reproduces the variables stored in the object, one must run the `verify` function.
If the verification succeeds, the object's state will be changed to _verified`, otherwise an error will be raised.

`teal_data` objects that are instantiated empty and can only become populated by evaluating code, are created verified.
Evaluating code in a `teal_data` object _does not_ change its verification status.

When retrieving code, unverified objects will always add a warning to the code stating that it has not passed verification.

```{r, message=FALSE, error=TRUE}
library(teal.data)
library(magrittr)

IRIS <- iris
IRIS$id <- seq_len(nrow(iris))

data_right <- teal_data(IRIS = IRIS, code = expression(IRIS <- iris, IRIS$id <- seq_len(nrow(iris))))
(data_right_verified <- verify(data_right)) # returns verified object

data_wrong <- teal_data(IRIS = IRIS, code = expression(iris <- iris, iris$id <- seq_len(nrow(iris))))
verify(data_wrong) # fails verification, raises error

data_naive <- teal_data()
data_naive <- within(data_naive, IRIS <- iris)
data_naive <- within(data_naive, IRIS$id <- seq_len(nrow(iris)))
data_naive # is verified
verify(data_naive) # runs without error
```

Find out more in the `teal_data()` documentation.
