#' Generate a teal_data dataset with sample data and JoinKeys
helper_generator_teal_data <- function() {
  iris2 <- iris
  iris2$id <- rnorm(NROW(iris2))
  iris2$id <- apply(iris2, 1, rlang::hash)
  new_teal_data(
    list(
      ds1 = iris2,
      ds2 = iris2
    ),
    code = "ds1 <- iris2; ds2 <- iris2",
    join_keys = helper_generator_JoinKeys("ds1", keys = c("id"))
  )
}

#' Generate a JoinKeys
helper_generator_JoinKeys <- function(dataset_1 = "ds1", keys = c("id")) { # nolint
  join_keys(
    join_key(dataset_1, keys = keys)
  )
}

#' Test suite for default join_keys generated by helper
helper_test_getter_join_keys <- function(obj, dataset_1 = "ds1") {
  jk <- join_keys(obj)

  expect_s3_class(jk, class = c("JoinKeys", "list"))
  expect_length(jk, 1)
  expect_length(jk[dataset_1, dataset_1], 1)

  obj
}

#' Test suite for JoinKeys after manual adding a primary key
helper_test_getter_join_keys_add <- function(obj, dataset_1 = "ds1", new_dataset_1 = "ds2", new_keys = c("id")) {
  obj <- helper_test_getter_join_keys(obj, dataset_1)
  join_keys(obj)[new_dataset_1] <- c(new_keys)

  jk <- join_keys(obj)

  expect_s3_class(jk, class = c("JoinKeys", "list"))
  expect_length(jk, 2)
  expect_length(jk[dataset_1, dataset_1], 1)
  expect_length(jk[new_dataset_1, new_dataset_1], 1)
}
