setOldClass("JoinKeys")

#' Reproducible data class.
#'
#' Reproducible data class basing on [teal.data::qenv-class].
#' @name teal_data-class
#' @rdname teal_data-class
#'
#' @slot code (`expression`) to reproduce the environment
#' @slot env (`environment`) environment which content was generated by the evaluation
#'  of the `code` slot.
#' @slot id (`integer`) random identifier of the code element to make sure uniqueness
#'  when joining.
#' @slot warnings (`character`) the warnings output when evaluating the code
#' @slot messages (`character`) the messages output when evaluating the code
#' @slot join_keys (`JoinKeys`) object
#' @slot datanames (`character`) names of datasets in `env`. Needed when non-dataset
#'  objects are needed in the `env` slot.
#'
#' @import teal.code
#' @keywords internal
setClass(
  Class = "teal_data",
  contains = "qenv",
  slots = c(join_keys = "JoinKeys", datanames = "character"),
  prototype = list(
    join_keys = join_keys(),
    datanames = character(0)
  )
)

#' Initialize `teal_data` object
#'
#' Initialize `teal_data` object.
#' @name new_teal_data
#'
#' @param code (`character(1)` or `language`) code to evaluate. Accepts and stores comments also.
#' @param data (`named list`) List of data.
#' @param keys (`JoinKeys`) object
#' @param datanames (`character`) names of datasets passed to `data`.
#'   Needed when non-dataset objects are needed in the `env` slot.
#'
#' @examples
#' new_teal_data(data = list(a = 1), code = quote(a <- 1))
#' new_teal_data(data = list(a = 1), code = parse(text = "a <- 1"))
#' new_teal_data(data = list(a = 1), code = "a <- 1")
#'
#' @export
setGeneric("new_teal_data", function(data = list(), code = character(), keys = join_keys(), datanames = character()) {
  standardGeneric("new_teal_data")
})

#' @rdname new_teal_data
#' @export
setMethod(
  "new_teal_data",
  signature = c(data = "list", code = "character", keys = "ANY"),
  function(data, code, keys = join_keys(), datanames = names(data)) {
    new_env <- rlang::env_clone(list2env(data), parent = parent.env(.GlobalEnv))
    lockEnvironment(new_env, bindings = TRUE)
    if (length(code) > 1) code <- paste(code, collapse = "\n")
    id <- sample.int(.Machine$integer.max, size = 1L)
    methods::new(
      "teal_data",
      env = new_env,
      code = code,
      warnings = "",
      messages = "",
      id = id,
      join_keys = keys,
      datanames = datanames
    )
  }
)

#' @rdname new_teal_data
#' @export
setMethod(
  "new_teal_data",
  signature = c(data = "list", code = "language", keys = "ANY"),
  function(data, code, keys = join_keys(), datanames = names(data)) {
    code_expr <- as.expression(code)
    new_teal_data(data = data, code = code_expr, keys = keys, datanames = datanames)
  }
)

#' @rdname new_teal_data
#' @export
setMethod(
  "new_teal_data",
  signature = c(data = "list", code = "expression", keys = "ANY"),
  function(data, code, keys = join_keys(), datanames = names(data)) {
    code_expr <- as.character(code)
    new_teal_data(data = data, code = code_expr, keys = keys, datanames = datanames)
  }
)
