#' (test helper) Generate a teal_data dataset with sample data and join_keys
#'
#' @return `teal_data`
#'
#' @keywords internal
local_teal_data <- function() {
  iris2 <- iris
  iris2$id <- rnorm(NROW(iris2))
  iris2$id <- apply(iris2, 1, rlang::hash)
  new_teal_data(
    list(
      ds1 = iris2,
      ds2 = iris2
    ),
    code = "ds1 <- iris2; ds2 <- iris2",
    join_keys = local_join_keys("ds1", keys = c("id"))
  )
}

#' (test helper) Generate a join_keys
#'
#' @param dataset_1 `character(1)` name of dataset to add.
#' @param keys `character(1)` primary key for `dataset_1` (optionally named).
#'
#' @return `join_keys` object with a primary key
#'
#' @keywords internal
local_join_keys <- function(dataset_1 = "ds1", keys = c("id")) { # nolint
  join_keys(
    join_key(dataset_1, keys = keys)
  )
}

#' (test helper) Test suite for default join_keys generated by helper
#'
#' @param obj Object with `join_keys` to perform operations (can be `join_keys`
#' or `teal_data`). It should only contain a primary key.
#' @param dataset_1 `character(1)` name of existing dataset to test.
#'
#' @return `obj` itself without any modifications
#'
#' @keywords internal
test_join_keys_bare <- function(obj, dataset_1 = "ds1") {
  jk <- join_keys(obj)

  expect_s3_class(jk, class = c("join_keys", "list"))
  expect_length(jk, 1)
  expect_length(jk[[dataset_1]][[dataset_1]], 1)

  obj
}

#' (test helper) Test suite for join_keys after manual adding a primary key
#'
#' @param obj Object with `join_keys` to perform operations (can be `join_keys`
#' or `teal_data`)
#' @param dataset_1 `character(1)` name of existing dataset.
#' @param new_dataset_1 `character(1)` name of new dataset to add.
#' @param new_keys
#'
#' @return `obj` itself modified with a new foreign key.
#'
#' @keywords internal
test_join_keys_add <- function(obj,
                               dataset_1 = "ds1",
                               new_dataset_1 = "ds2",
                               new_keys = c("id")) {
  obj <- test_join_keys_bare(obj, dataset_1)
  join_keys(obj)[new_dataset_1] <- c(new_keys) # primary key

  jk <- join_keys(obj)

  expect_s3_class(jk, class = c("join_keys", "list"))
  expect_length(jk, 2)
  expect_length(jk[[dataset_1]][[dataset_1]], 1)
  expect_length(jk[[new_dataset_1]][[new_dataset_1]], 1)
}

#' (test helper) Test suite for join_keys that performs a mass modification
#'
#' The goal of this helper is to modify the `join_keys` with all variants of a
#' valid foreign key.
#'
#' @param obj Object with `join_keys` to perform operations (can be `join_keys`
#' or `teal_data`)
#'
#' @return `obj` itself modified with a new foreign key.
#'
#' @keywords internal
test_join_keys_combinatory <- function(obj) {
  obj <- test_join_keys_bare(obj, "ds1")

  counter <- 2
  .ds <- function(add = 1, prefix = "ds") {
    counter <<- counter + add
    paste0(prefix, "-", counter - add)
  }

  .key <- function(type = 1, prefix = "col") {
    col_name <- .ds(add = 1, prefix = prefix)
    switch(type,
      "1" = col_name,
      "2" = setNames(col_name, col_name),
      "3" = setNames(col_name, paste0(col_name, "-diff")),
      "4" = setNames("", paste0(col_name))
    )
  }

  # Primary key (each adds 1)
  join_keys(obj)[.ds()] <- .key()
  expect_error(join_keys(obj)[.ds()] <- .key(3))

  join_keys(obj) <- c(join_keys(obj), join_key(.ds(add = 0), .ds(), .key(1)))
  join_keys(obj) <- c(join_keys(obj), join_key(.ds(add = 0), .ds(), .key(2)))
  join_keys(obj) <- c(join_keys(obj), join_key(.ds(add = 0), .ds(), .key(4)))
  join_keys(obj) <- c(join_keys(obj), join_key(.ds(add = 0), .ds(), character(0)))
  expect_error(join_keys(obj) <- c(join_keys(obj), join_key(.ds(add = 0), .ds(), .key(3))))

  # Relationship pair (each adds 2)
  join_keys(obj)[[.ds()]][[.ds()]] <- .key(1)
  join_keys(obj)[[.ds()]][[.ds()]] <- .key(2)
  join_keys(obj)[[.ds()]][[.ds()]] <- .key(3)
  join_keys(obj)[[.ds()]][[.ds()]] <- .key(4)
  join_keys(obj)[[.ds()]][[.ds()]] <- character(0)

  # Relationship pair alternative (each adds 2)
  join_keys(obj)[[.ds()]] <- setNames(list(.key(1)), .ds())
  join_keys(obj)[[.ds()]] <- setNames(list(.key(2)), .ds())
  join_keys(obj)[[.ds()]] <- setNames(list(.key(3)), .ds())
  join_keys(obj)[[.ds()]] <- setNames(list(.key(4)), .ds())
  join_keys(obj)[[.ds()]] <- setNames(list(character(0)), .ds())

  # Using join_key (each adds 2)
  join_keys(obj) <- c(join_keys(obj), join_key(.ds(), .ds(), .key(1)))
  join_keys(obj) <- c(join_keys(obj), join_key(.ds(), .ds(), .key(2)))
  join_keys(obj) <- c(join_keys(obj), join_key(.ds(), .ds(), .key(3)))
  join_keys(obj) <- c(join_keys(obj), join_key(.ds(), .ds(), .key(4)))
  join_keys(obj) <- c(join_keys(obj), join_key(.ds(), .ds(), character(0)))

  # (each join_key adds 2)
  join_keys(obj) <- c(
    join_keys(obj),
    join_key(.ds(), .ds(), .key(1)),
    join_key(.ds(), .ds(), .key(2)),
    join_key(.ds(), .ds(), .key(3)),
    join_key(.ds(), .ds(), .key(4)),
    join_key(.ds(), .ds(), character(0))
  )

  # (each join_key adds 2)
  join_keys(obj) <- c(
    join_keys(obj), join_keys(
      join_key(.ds(), .ds(), .key(1)),
      join_key(.ds(), .ds(), .key(2)),
      join_key(.ds(), .ds(), .key(3)),
      join_key(.ds(), .ds(), .key(4)),
      join_key(.ds(), .ds(), character(0))
    )
  )

  expect_s3_class(join_keys(obj), class = c("join_keys", "list"))

  expected_length <- 55 + 1 # 68 from the operations + 1 from `helper_test_getter_join_keys`
  expect_length(join_keys(obj), expected_length)

  join_keys(obj) <- c(join_keys(obj), join_key("ds-manual", .ds(), .key(1)))
  expect_length(join_keys(obj), expected_length + 2) # adds 2 new datasets

  join_keys(obj) <- c(join_keys(obj), join_key(.ds(), "ds-manual", .key(1)))
  expect_length(join_keys(obj), expected_length + 2 + 1) # adds 1 new dataset as ds-manual already exists
}

#' (test helper) Create test data for CDISC data
#'
#' @inheritParams cdisc_data
#' @param join_keys (`join_keys`) or a single (`join_key_set`)\cr
#'   (optional) object with dataset column relationships used for joining.
#'   If empty then no joins between pairs of objects.
#'
#' @return a cdisc data of `ADSL`, `ADTTE` and `ADAE`
#'
#' @keywords internal
local_cdisc_data_mixed_call <- function(check = TRUE, join_keys1 = cdisc_join_keys()) {
  adsl_raw <- as.data.frame(as.list(setNames(nm = get_cdisc_keys("ADSL"))))
  adtte_raw <- as.data.frame(as.list(setNames(nm = get_cdisc_keys("ADTTE"))))
  adae_raw <- as.data.frame(as.list(setNames(nm = get_cdisc_keys("ADAE"))))

  adsl <- cdisc_dataset(
    dataname = "ADSL",
    x = adsl_raw,
    code = "ADSL <- as.data.frame(as.list(setNames(nm = get_cdisc_keys(\"ADSL\"))))"
  )
  adtte_cf <- callable_function(
    function() {
      as.data.frame(as.list(setNames(nm = get_cdisc_keys("ADTTE"))))
    }
  )
  adtte <- cdisc_dataset_connector("ADTTE", adtte_cf, keys = get_cdisc_keys("ADTTE"), vars = list(x = adsl))
  adae_cf <- callable_function(
    function() {
      as.data.frame(as.list(setNames(nm = get_cdisc_keys("ADAE"))))
    }
  )
  adae_cdc <- cdisc_dataset_connector("ADAE", adae_cf, keys = get_cdisc_keys("ADAE"))
  adae_rdc <- cdisc_data_connector(
    connection = data_connection(open_fun = callable_function(function() "open function")),
    connectors = list(adae_cdc)
  )

  load_dataset(adsl)
  load_dataset(adtte)
  load_dataset(adae_cdc)

  cdisc_data(adsl, adtte, adae_rdc, check = check, join_keys = join_keys1)
}
